name: example
description: this example demonestrate the usage of grafpix icon package for your flutter applications.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  grafpix:
    path: ../

flutter:
  uses-material-design: true